"""Merged view of config/targets.yaml (pilot, hand-maintained) and
config/targets_national.yaml (generated by build_national_targets.py).

Sources call load_targets() and see ONE config. Merge rules:
  - dicts merge recursively; where both define the same scalar, targets.yaml wins
    (hand-tuned pilot values always beat generated defaults)
  - lists concatenate (pilot first), deduped by 'url'/'feed'/'name' for dicts
    or by value for scalars — so a feed curated by hand in targets.yaml is never
    duplicated by its generated twin
  - targets_national.yaml is optional: with only the pilot file present this
    returns exactly the old config (pilot behaviour unchanged)
"""
from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parent.parent
PILOT = PROJECT_ROOT / "config" / "targets.yaml"
NATIONAL = PROJECT_ROOT / "config" / "targets_national.yaml"


def _key(v):
    if isinstance(v, dict):
        return v.get("url") or v.get("feed") or v.get("name") or repr(sorted(v.items()))
    return v


def _merge_lists(pilot: list, national: list) -> list:
    seen, out = set(), []
    for item in list(pilot) + list(national):
        k = _key(item)
        if k in seen:
            continue
        seen.add(k)
        out.append(item)
    return out


def _merge(pilot, national):
    if isinstance(pilot, dict) and isinstance(national, dict):
        out = dict(national)
        for k, v in pilot.items():
            out[k] = _merge(v, national[k]) if k in national else v
        return out
    if isinstance(pilot, list) and isinstance(national, list):
        return _merge_lists(pilot, national)
    return pilot  # scalar conflict: hand-maintained pilot value wins


def load_targets() -> dict:
    pilot = yaml.safe_load(PILOT.read_text()) or {}
    if not NATIONAL.exists():
        return pilot
    national = yaml.safe_load(NATIONAL.read_text()) or {}
    return _merge(pilot, national)


if __name__ == "__main__":
    cfg = load_targets()
    for key, val in cfg.items():
        if isinstance(val, list):
            print(f"{key}: {len(val)} entries")
        elif isinstance(val, dict):
            inner = {k: (len(v) if isinstance(v, list) else v) for k, v in val.items()}
            print(f"{key}: {inner}")
        else:
            print(f"{key}: {val}")
